### ISSUE TITLE
error verifying otp code

### ISSUE THREAD

**Issue by Arnootn** [chemokita13/BeRealGate#2]
i tried everything i could; running it local or using a hosting website; but this message persists.

**Comment by chemokita13** [comment]
The error is in https://github.com/chemokita13/BeRealGate/blob/main/src/app/login/page.tsx line 69, I have to change otpSesion to otpSession with 2 's': 'ss' but i dont have time.  If you wont you couldo do a pull request to be deployed or change and run it locally

**Comment by chemokita13** [comment]
Solved!
