### ISSUE TITLE
Post bereal over the app

### ISSUE THREAD

**Issue by Leandro12341** [chemokita13/BeRealGate#3]

**Comment by chemokita13** [comment]
Hey! Can you bring more details about the issue ?

**Comment by Leandro12341** [comment]
> Hey! Can you bring more details about the issue ?

I mean that you make that people can post over your app

**Comment by chemokita13** [comment]
It is possible but is in an alpha version, you can use that and send feedback
https://berealgate.vercel.app/posts/new

**Comment by Leandro12341** [comment]
> It is possible but is in an alpha version, you can use that and send feedback
> https://berealgate.vercel.app/posts/new

When I try to post it says error

**Comment by chemokita13** [comment]
> > It is possible but is in an alpha version, you can use that and send feedback
> > https://berealgate.vercel.app/posts/new
> 
> When I try to post it says error

Let me some time to avoid that

**Comment by chemokita13** [comment]
I think is working, but not as well I want. You can try it and if throws error, restart the page. If the error persit let me know to solve it

**Comment by Leandro12341** [comment]
> I think is working, but not as well I want. You can try it and if throws error, restart the page. If the error persit let me know to solve it

It works but the photo don’t fit in the boxes from BeReal so you can see that is not a BeReal

**Comment by chemokita13** [comment]
Try it again @Leandro12341 !
But you shouldn't use high memomry images because the server run out of memory, I think to be all ok, less than 160kb is fine

**Comment by Leandro12341** [comment]
> Try it again @Leandro12341 !
> But you shouldn't use high memomry images because the server run out of memory, I think to be all ok, less than 160kb is fine

Unfortunately the problem is still there, so if you go to the comments under the post you can see that it is a fake because the picture doesn't fit into the picture box

**Comment by chemokita13** [comment]
Do you mean about the picture resolution? I think is because Bereal default app resize the image to 2000*1500 but my API is not doing that. Can you try with a 2000*1500 img to see if the problem solves for making the feature?

**Comment by Leandro12341** [comment]
> Do you mean about the picture resolution? I think is because Bereal default app resize the image to 2000_1500 but my API is not doing that. Can you try with a 2000_1500 img to see if the problem solves for making the feature?

When I try to post it with 2000 1500 it still doesn't fit in the box I would send you a screenshot but it's difficult to do via GitHub

**Comment by chemokita13** [comment]
> > Do you mean about the picture resolution? I think is because Bereal default app resize the image to 2000_1500 but my API is not doing that. Can you try with a 2000_1500 img to see if the problem solves for making the feature?
> 
> When I try to post it with 2000 1500 it still doesn't fit in the box I would send you a screenshot but it's difficult to do via GitHub

Could you send me a screenshot via e-mail? chemokita@proton.me

**Comment by Leandro12341** [comment]
> > > Do you mean about the picture resolution? I think is because Bereal default app resize the image to 2000_1500 but my API is not doing that. Can you try with a 2000_1500 img to see if the problem solves for making the feature?
> > 
> > 
> > When I try to post it with 2000 1500 it still doesn't fit in the box I would send you a screenshot but it's difficult to do via GitHub
> 
> Could you send me a screenshot via e-mail? [chemokita@proton.me](mailto:chemokita@proton.me)

I send you a mail

**Comment by chemokita13** [comment]
Yeah, I catch it, I think the problem is the image size, let me add the feature of cropping the image to my API!
@Leandro12341

**Comment by Leandro12341** [comment]
> Yeah, I catch it, I think the problem is the image size, let me add the feature of cropping the image to my API!
> @Leandro12341

Ok thanks

**Comment by Leandro12341** [comment]
> > Yeah, I catch it, I think the problem is the image size, let me add the feature of cropping the image to my API!
> > @Leandro12341
> 
> Ok thanks

Hello, is it working now?

**Comment by chemokita13** [comment]
> > > Yeah, I catch it, I think the problem is the image size, let me add the feature of cropping the image to my API!
> > > @Leandro12341
> > 
> > Ok thanks
> 
> Hello, is it working now?

No yet

**Comment by Leandro12341** [comment]
> > > > Yeah, I catch it, I think the problem is the image size, let me add the feature of cropping the image to my API!
> > > > @Leandro12341
> > > 
> > > 
> > > Ok thanks
> > 
> > 
> > Hello, is it working now?
> 
> No yet

Ok could you write under my comment if it working

**Comment by chemokita13** [comment]
> > > > > Yeah, I catch it, I think the problem is the image size, let me add the feature of cropping the image to my API!
> > > > > @Leandro12341
> > > > 
> > > > 
> > > > Ok thanks
> > > 
> > > 
> > > Hello, is it working now?
> > 
> > 
> > No yet
> 
> Ok could you write under my comment if it working

Try it now! @Leandro12341

**Comment by Leandro12341** [comment]
> > > It is possible but is in an alpha version, you can use that and send feedback
> > > https://berealgate.vercel.app/posts/new
> > 
> > 
> > When I try to post it says error
> 
> Let me some time to avoid that

Thank 

> > > > > > Yeah, I catch it, I think the problem is the image size, let me add the feature of cropping the image to my API!
> > > > > > @Leandro12341
> > > > > 
> > > > > 
> > > > > Ok thanks
> > > > 
> > > > 
> > > > Hello, is it working now?
> > > 
> > > 
> > > No yet
> > 
> > 
> > Ok could you write under my comment if it working
> 
> Try it now! @Leandro12341

Thank yo so much it’s working now
